version: "3.7"
services:
  server:
    image: nodejs-docker:1.0.0
    environment:
      TYPE: 'test'

    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - servernet
networks:
  servernet:
